=== chenyunecjtu/scatter/bin/wsserver-config-schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "http://example.com/example.json",
  "type": "object",
  "properties": {
    "server": {
      "$id": "/properties/server",
      "type": "object",
      "properties": {
        "endpoint": {
          "$id": "/properties/server/properties/endpoint",
          "type": "string",
          "title": "The Endpoint Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "/chat"
          ]
        },
        "address": {
          "$id": "/properties/server/properties/address",
          "type": "string",
          "title": "The Address Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "*"
          ]
        },
        "port": {
          "$id": "/properties/server/properties/port",
          "type": "integer",
          "title": "The Port Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            8080
          ]
        },
        "workers": {
          "$id": "/properties/server/properties/workers",
          "type": "integer",
          "title": "The Workers Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": 0,
          "examples": [
            16
          ]
        },
        "secure": {
          "$id": "/properties/server/properties/secure",
          "type": "object",
          "properties": {
            "enabled": {
              "$id": "/properties/server/properties/secure/properties/enabled",
              "type": "boolean",
              "title": "The Enabled Schema.",
              "description": "An explanation about the purpose of this instance.",
              "default": false,
              "examples": [
                false
              ]
            },
            "crtPath": {
              "$id": "/properties/server/properties/secure/properties/crtPath",
              "type": "string",
              "title": "The Crtpath Schema.",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "../certs/debug.crt"
              ]
            },
            "keyPath": {
              "$id": "/properties/server/properties/secure/properties/keyPath",
              "type": "string",
              "title": "The Keypath Schema.",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "../cert/debug.key"
              ]
            }
          },
          "required": [
            "enabled",
            "crtPath",
            "keyPath"
          ]
        },
        "tmpDir": {
          "$id": "/properties/server/properties/tmpDir",
          "type": "string",
          "title": "The Tmpdir Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": "",
          "examples": [
            "/tmp"
          ]
        }
      },
      "required": [
        "endpoint",
        "address",
        "port"
      ]
    },
    "restApi": {
      "$id": "/properties/restApi",
      "type": "object",
      "properties": {
        "enabled": {
          "$id": "/properties/restApi/properties/enabled",
          "type": "boolean",
          "title": "The Enabled Schema.",
          "description": "An explanation about the purpose of this instance.",
          "default": false,
          "examples": [
            false
          ]
        },
        "auth": {
          "$id": "/properties/restApi/properties/auth",
          "type": "object",
          "properties": {
            "basic": {
              "$id": "/properties/restApi/properties/auth/properties/basic",
              "type": "object",
              "properties": {
                "user": {
                  "$id": "/properties/restApi/properties/auth/properties/basic/properties/user",
                  "type": "string",
                  "title": "The User Schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "",
                  "examples": [
                    "chat_user"
                  ]
                },
                "password": {
                  "$id": "/properties/restApi/properties/auth/properties/basic/properties/password",
                  "type": "string",
                  "title": "The Password Schema.",
                  "description": "An explanation about the purpose of this instance.",
                  "default": "",
                  "examples": [
                    "chat_password"
                  ]
                }
              }
            }
          }
        }
      },
      "required": [
        "enabled",
        "auth"
      ]
    },
    "chat": {
      "$id": "/properties/chat",
      "type": "object",
      "properties": {
        "message": {
          "$id": "/properties/chat/properties/message",
          "type": "object",
          "properties": {
            "maxSize": {
              "$id": "/properties/chat/properties/message/properties/maxSize",
              "type": "string",
              "title": "The Maxsize Schema.",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "10M"
              ]
            }
          }
        }
      }
    },
    "event": {
      "$id": "/properties/event",
      "type": "object",
      "properties": {
        "postback": {
          "$id": "/properties/event/properties/postback",
          "type": "object",
          "properties": {
            "url": {
              "$id": "/properties/event/properties/postback/properties/url",
              "type": "string",
              "title": "The Url Schema.",
              "description": "An explanation about the purpose of this instance.",
              "default": "",
              "examples": [
                "http://example.com/postback"
              ]
            },
            "auth": {
              "$id": "/properties/event/properties/postback/properties/auth",
              "type": "object",
              "properties": {
                "basic": {
                  "$id": "/properties/event/properties/postback/properties/auth/properties/basic",
                  "type": "object",
                  "properties": {
                    "user": {
                      "$id": "/properties/event/properties/postback/properties/auth/properties/basic/properties/user",
                      "type": "string",
                      "title": "The User Schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "default": "",
                      "examples": [
                        "username"
                      ]
                    },
                    "password": {
                      "$id": "/properties/event/properties/postback/properties/auth/properties/basic/properties/password",
                      "type": "string",
                      "title": "The Password Schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "default": "",
                      "examples": [
                        "password"
                      ]
                    }
                  },
                  "required": [
                    "user",
                    "password"
                  ]
                },
                "header": {
                  "$id": "/properties/event/properties/postback/properties/auth/properties/header",
                  "type": "object",
                  "properties": {
                    "name": {
                      "$id": "/properties/event/properties/postback/properties/auth/properties/header/properties/name",
                      "type": "string",
                      "title": "The Name Schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "default": "",
                      "examples": [
                        "X-Auth-Token"
                      ]
                    },
                    "value": {
                      "$id": "/properties/event/properties/postback/properties/auth/properties/header/properties/value",
                      "type": "string",
                      "title": "The Value Schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "default": "",
                      "examples": [
                        "AUTH_TOKEN"
                      ]
                    }
                  },
                  "required": [
                    "name",
                    "value"
                  ]
                },
                "bearer": {
                  "$id": "/properties/event/properties/postback/properties/auth/properties/bearer",
                  "type": "object",
                  "properties": {
                    "value": {
                      "$id": "/properties/event/properties/postback/properties/auth/properties/bearer/properties/value",
                      "type": "string",
                      "title": "The Value Schema.",
                      "description": "An explanation about the purpose of this instance.",
                      "default": "",
                      "examples": [
                        "AUTH_TOKEN"
                      ]
                    }
                  },
                  "required": [
                    "value"
                  ]
                }
              }
            }
          },
          "required": [
            "url"
          ]
        }
      }
    }
  },
  "required": [
    "server"
  ]
}

=== chenyunecjtu/scatter/bin/wsserver.json
{
  "server": {
    "endpoint": "/chat",
    "address": "*",
    "port": 8080,
    "workers": 16,
    "secure": {
      "enabled": false,
      "crtPath": "../certs/debug.crt",
      "keyPath": "../cert/debug.key"
    },
    "tmpDir": "/tmp"
  },
  "restApi": {
    "enabled": false,
    "auth": {
      "basic": {
        "user": "chat_user",
        "password": "chat_password"
      }
    }
  },
  "chat": {
    "message": {
      "maxSize": "10M"
    }
  },
  "event": {
    "enabled": true,
    "enableRetry": true,
    "retryIntervalSeconds": 10,
    "retryCount": 3,
    "targets": [
      {
        "type": "postback",
        "url": "http://localhost"
      }
    ]
  }
}
